### ISSUE TITLE
Формирование keystore

### ISSUE THREAD

**Issue by VitalyVaryvdin** [BlackSan11/esia-crypto#4]
Добрый день, формирую p12 с помощью openssl из выхлопа P12FromGostCSP. При подписи запроса стабильно выдает подпись отличную от той, которую формирует расширение КриптоПРО и, соответственно, ЕСИА отвечает, что client_secret неправильный.

Не совсем понимаю куда копать, с КриптоПРО и ЕСИА до этого не работал, но поздреваю, что keystore сформирован неправильно. Сертификат, зарегистрированный в ЕСИА и используемый в коде - одинаковые

Linux, signature algo сертификата - GOST R 34.11-2012/256 with GOST R 34.10-2012 256-bit curve

использую так:

```java
            Supplier<KeyStore> keyStoreSupplier = () -> {
				try (InputStream stream = new FileInputStream(keyStorePath)) {
					KeyStore store = KeyStore.getInstance("PKCS12");
					store.load(stream, keyStorePassword.toCharArray());
					return store;
				} catch (Exception e) {
					System.out.println("Failed to load keystore");
					throw new RuntimeException(e);
				}
			};

	    EsiaSigner esiaSigner = EsiaSigner.builder()
               .keyStoreSupplier(keyStoreSupplier)
               .privateKeyPasswordSupplier(() -> keyPassword)
               .signingCertificateAliasSupplier(() -> certificateAlias)
               .build();

            byte[] data = toSign.toString().getBytes(StandardCharsets.UTF_8);
            byte[] secretBytes = esiaSigner.signPkcs7(data);
            return Base64.encodeBase64URLSafeString(secretBytes);
```

**Comment by BlackSan11** [comment]
@VitalyVaryvdin 

Добрый день!
1. Подскажите, что за объект toSign и как у него реализован toString()?
2. Сейчас еще раз проверил, для нас работает такая конструкция:
`String signingString = <esiaAuthScope> + <formattedTimestamp> + <esiaClientId> + <state>;`
`byte[] resultSignature = esiaSigner.signPkcs7(signingString.getBytes(StandardCharsets.UTF_8));`
`String clientSecret = Base64.getUrlEncoder().encodeToString(resultSignature);`

**Comment by VitalyVaryvdin** [comment]
@BlackSan11 

toSign - StringBuilder

По теме - keystore был сформирован правильно, ЕСИА воспринимает сертификаты как одинаковые.

Моя основная ошибка оказалось в том, что endpoint v2 ждет сырую подпись, а не pkcs#7. Старый endpoint не рекомендуют к использованию в новых интеграциях. Не пробовал данную подпись со старым endpoint.

Сейчас использую вызов `csptest` для формирования raw подписи. Проблема с ЕСИА осталась нерешенной - все так же возвращает clientSecretWrong. Документация крайне плачевная, два разных пункта методических рекомендаций описывают одно и то же совсем по-разному - в одном пункте в client_secret нужно класть 6 параметров, в другом - 5. Но тем не менее, проблема отношения к данной библиотеке не имеет. Issue, думаю, можно закрыть.
